### ISSUE TITLE
Отзыв 07.02.2014

### ISSUE THREAD

**Issue by bodrovis** [Alexrosh92/GuitarMaster#1]
1. Все лишние файлы из javascripts и stylesheets следует удалить
2. https://github.com/Alexrosh92/GuitarMaster/blob/master/app/assets/stylesheets/application.css.scss#L12 так нельзя делать. Либо только `require`, либо только `import`
3. Удалить index.html из public, иначе маршрут по умолчанию не открывается
4. Зачем в layouts файл home.html.erb?

Пока так, хотелось бы увидеть рабочее приложение на Heroku, тогда поговорим ещё. Если что-то не будет получаться, пиши сюда.

**Comment by Alexrosh92** [comment]
Привет Илья, всё что ты просил я поправил. Вот сайт на Heroku http://guitarmaster.herokuapp.com/
