### ISSUE TITLE
Отзыв 10.02.2014

### ISSUE THREAD

**Issue by bodrovis** [Alexrosh92/GuitarMaster#2]
1. По подбору цветов тут обсуждать ничего не будем, но скажу, что он не самый лучший (в частности,  в меню). Так или иначе, за это обычно отвечает дизайнер
2. На главной странице внизу изображения - они слишком большие (я имею ввиду оригинальные размеры). Суть очень простая - мы заставляем пользователя грузить большие изображения, а потом всё равно в браузере их сжимаем до более мелких. Так делать нехорошо, надо сразу сжать изображения до нужного размера. Кстати, для изображений также надо указать альтернативный текст.
3. Страницу с аккордами надо как-то оформить. Таблицей, например, или списком.
4. Также добавь футер с копирайтами (условными) - не обязательно делать его прилипшим к низу

Вообще проект получился очень простым - одни скаффолды. Доп задания:
1. Внедрить библиотеку `will_paginate` (которая, кстати, уже подключена к проекту)
2. Внедрить пару виджетов jQuery UI: http://jqueryui.com/ (например, аккордион, вкладки, всплывающая подсказка). Для этого можно использовать библиотеку jquery-ui-rails
3. Добавить на страницу Контакты интерактивную карту Google или Yandex с указанием местоположения офиса (любое, хоть в Зимбабве)

**Comment by Alexrosh92** [comment]
Привет Илья.  Твои замечания исправил, дополнительное задание выполнил. http://guitarmaster.herokuapp.com/

**Comment by bodrovis** [comment]
1. Новые аккорды не добавляются, вылезает ошибка
2. Делать `require jquery.ui.all` - плохая идея, грузится много лишнего. Нужно грузить только те виджеты, которые реально используются на сайте

**Comment by Alexrosh92** [comment]
1. Я посмотрел, запись с аккордом в базе данных создавалась, но он не отображался. Скорее всего это из-за того, что ты вписывал video_url из адресной строки ютуба, а я предполагал брать его из вкладки "Поделиться"---->HTML-код, в таком виде //www.youtube.com/embed/cBYXkqqoflM.
   Сейчас я это исправил, подключил гем https://github.com/dejan/auto_html
   Теперь при добавлении аккорда можно вписывать в video_url ссылку с адресной строки
2. Исправил, подключил только то что надо;

На хероку залил, обновил.

**Comment by Alexrosh92** [comment]
Привет Илья, ты видел мои изменения?

**Comment by bodrovis** [comment]
@Alexrosh92 Видел, пока всё.

**Comment by Alexrosh92** [comment]
Привет Илья, я сделал дополнительное задание. Информацию брал тут http://www.radiant-wind.com/categories/javascript-css-html/posts/stilizatsiya-polya-dlya-zagruzki-fayla
На heroku залил.

**Comment by bodrovis** [comment]
Как показалась статья? Достаточно понятно объясняется?

**Comment by Alexrosh92** [comment]
Статья хорошая. Достаточно подробно все написано, у меня не возникло трудностей, когда на своем сайте кнопку стилизовал.

**Comment by bodrovis** [comment]
Хорошо. Проблема в том, что когда я выбираю файл для загрузки, его имя не пишется в текстовом поле.

**Comment by Alexrosh92** [comment]
ага, забыл про это(( Сейчас поправлю.

**Comment by Alexrosh92** [comment]
Всё, теперь отображает имя файла в текстовом поле.

**Comment by bodrovis** [comment]
У меня что-то нет

**Comment by Alexrosh92** [comment]
У меня всё нормально работает. Не могу понять в чём причина, я и с хрома заливаю всё норм и с мозилы. А у тебя какой браузер?

**Comment by bodrovis** [comment]
А, это из-за смешанного содержимого на странице. Если открывать https то он блокирует скрипты, которые грузятся по http, в частности яндекс карты, а вместе с ним и часть других. Но ладно. Так или иначе, маска наложена неровно и юзер может промахнуться и нажать не на ту кнопку.

**Comment by Alexrosh92** [comment]
Поправил, теперь маска наложена ровно. Илюх, я сдал?

**Comment by bodrovis** [comment]
Вот теперь хорошо. Думаю, да
